# Generated by Django 6.1.1 on 2026-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='repeats',
            field=models.BooleanField(default=False),
        ),
    ]
