# Generated by Django 6.1.1 on 2026-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_income_repeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
